name: agentic_ios_ready
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  speech_to_text: ^6.3.0
  flutter_tts: ^3.8.3
  http: ^0.13.6
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: false
  ios: true
  image_path_ios: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
